### ISSUE TITLE
起動時例外 blender 2.83

### ISSUE THREAD

**Issue by listelin** [trzr/Blender-CM3D2-Converter#1]
2.82aでは利用出来ていましたが、2.83では以下の例外がでて利用できなくなりました

Exception in module register(): C:\Users\xxx\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\CM3D2 Converter\__init__.py
Traceback (most recent call last):
  File "C:\blender\2.83\2.83\scripts\modules\addon_utils.py", line 382, in enable
    mod.register()
  File "C:\Users\xxx\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\CM3D2 Converter\__init__.py", line 317, in register
    if not system.use_international_fonts:
AttributeError: 'PreferencesView' object has no attribute 'use_international_fonts'
_______REgister previews

**Comment by trzr** [comment]
報告ありがとうございます。

2.83の調査もできておらず、あまり確認に時間を掛けられていない状況です。
一応暫定ながら、上記エラーへの対応は行いました。
